# Generated by Django 5.0.3 on 2024-03-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidades', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades en general',
            },
        ),
        migrations.AlterModelOptions(
            name='empleadosmodel',
            options={'verbose_name': 'Empleados', 'verbose_name_plural': 'Empleados de la empresa'},
        ),
    ]
