# Generated by Django 5.0.3 on 2024-03-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_habilidades_alter_empleadosmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadosmodel',
            name='Habilidades',
            field=models.ManyToManyField(to='empleados.habilidades'),
        ),
    ]
