# Generated by Django 5.0.3 on 2024-03-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleadosmodel_habilidades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilidades',
            new_name='HabilidadesModel',
        ),
    ]
